name: Run Newman Tests

on:
  push:
    branches:
      - main      # Trigger this workflow on push to the main branch
  pull_request:
    branches:
      - main      # Trigger this workflow on pull requests targeting the main branch

jobs:
  newman-test:
    runs-on: ubuntu-latest    # You can also use macos-latest or windows-latest if needed

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js version 22
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'   # Update Node.js version to 22

      # Step 3: Install Newman globally
      - name: Install Newman globally
        run: npm install -g newman
        working-directory: ./src  # Set the working directory to `src` where `package.json` is

      # Step 4: Install local dependencies from package.json
      - name: Install local dependencies
        run: npm install
        working-directory: ./src  # Again, ensure `npm install` runs in the `src` directory

      - name: List files in src directory for debugging
        run: |
          ls -R ./src

      - name: Run Newman tests
        run: |
          newman run ./src/postman_collections/Test.postman_collection.json \
            --reporters cli,html,json \
            --reporter-html-export ./newman/newman-report.html \
            --reporter-json-export ./newman/newman-report.json
        working-directory: ./src   # Ensure this is the correct directory for the collection

      # Step 6: Upload the HTML report as an artifact (optional)
      - name: Upload HTML Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: newman-html-report
          path: ./newman/newman-report.html

      # Step 7: Upload the JSON report as an artifact (optional)
      - name: Upload JSON Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: newman-json-report
          path: ./newman/newman-report.json
